### ISSUE TITLE
It won't open in Chrome

### ISSUE THREAD

**Issue by zhangjiaxin281** [alexpusch/awesome-rabbitmq-chrome#1]
Google Chrome版本:72.0.3626.121 It won't open in Chrome

**Comment by alexpusch** [comment]
what version of RabbitMQ?

**Comment by zhangjiaxin281** [comment]
RabbitMQ:3.7.12  Clicking on the icon does not start Awesome RabbitMQ Management

**Comment by alexpusch** [comment]
@zhangjiaxin281 I can see no issues on my Chrome 72 + RabbitMQ 3.7.12

Can you check if there are errors in the chrome dev console?

**Comment by zhangjiaxin281** [comment]
There was no error. I added an application to the Chrome browser and clicked start.

**Comment by alexpusch** [comment]
Oh, wait did you mean you clicked on the icon in the Chrome icon tray (top left in Chrome)? Thats just an indicator for when the extension in active. To access the management panel just go to your regular RabbitMQ management page. You will see an "Awesome" tab next to the "Queues".

**Comment by zhangjiaxin281** [comment]
Thank you very much for your patient answer. I have understood what you said. Thank you again.
